application: kl1885-ost-14fall
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /myimage/.*
  script: py.image.app

- url: /rss
  script: py.rss.app

- url: /rss/.*
  script: py.rss.app

- url: /question
  script: py.question.app

- url: /question/.*
  script: py.question.app

- url: /questionhome
  script: py.homepage.app

- url: /questionhome/.*
  script: py.homepage.app

- url: /sort
  script: py.homepage.app

- url: /.*
  script: py.homepage.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
