application: kl1885-ost-14fall
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: .*
  script: py.main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
