application: kl1885-ost-14fall
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /vote
  script: py.vote.app

- url: /vote.*
  script: py.vote.app

- url: /question
  script: py.question.app

- url: /question/answer
  script: py.answer.app

- url: /question/answer/.*
  script: py.answer.app

- url: /question/.*
  script: py.question.app

- url: /homepage
  script: py.homepage.app

- url: /.*
  script: py.homepage.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
